apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipelines-dotnetcore-api
  name: pipelines-dotnetcore-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelines-dotnetcore-api
  template:
    metadata:
      labels:
        app: pipelines-dotnetcore-api
    spec:
      containers:
        - image: quay.io/rh-ee-srehman/dotnetcore:latest
          imagePullPolicy: Always
          name: pipelines-dotnetcore-api
          ports:
            - containerPort: 80
              protocol: TCP
